package fwd.view;

import fwd.controller.Controller;
import fwd.model.HeaderTableModel;
import fwd.model.InvoiceHeader;
import fwd.model.LineTableModel;

import java.util.ArrayList;
import javax.swing.*;

/**
 *
 * @author m7md_
 */
public class FWD_InvoiceGenerator extends javax.swing.JFrame {

    public FWD_InvoiceGenerator() {
        //controller = new Controller(this);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        headerTbl = new javax.swing.JTable();
        headerTbl.getSelectionModel().addListSelectionListener(controller);

        jScrollPane2 = new javax.swing.JScrollPane();
        itemTbl = new javax.swing.JTable();
        label1 = new javax.swing.JLabel();
        label2 = new javax.swing.JLabel();
        label3 = new javax.swing.JLabel();
        lable4 = new javax.swing.JLabel();
        invNoLbl = new javax.swing.JLabel();
        invTotalLbl = new javax.swing.JLabel();
        newInvBtn = new javax.swing.JButton();
        newInvBtn.addActionListener(controller);
        deleteInvBtn = new javax.swing.JButton();
        deleteInvBtn.addActionListener(controller);
        newItemBtn = new javax.swing.JButton();
        newItemBtn.addActionListener(controller);
        deleteItemBtn = new javax.swing.JButton();
        deleteItemBtn.addActionListener(controller);
        invDateLbl = new javax.swing.JLabel();
        invCustNameLbl = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        file = new javax.swing.JMenu();
        loadFile = new javax.swing.JMenuItem();
        loadFile.addActionListener(controller);
        saveChanges = new javax.swing.JMenuItem();
        saveChanges.addActionListener(controller);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        headerTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "No.", "Date", "Customer", "Total"
            }
        ));
        jScrollPane1.setViewportView(headerTbl);

        itemTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "No.", "Item Name", "Item Price", "Count", "Item Total"
            }
        ));
        jScrollPane2.setViewportView(itemTbl);

        label1.setText("Invoice Number");

        label2.setText("Invoice Date");

        label3.setText("Customer Name");

        lable4.setText("Invoice Total");

        invNoLbl.setText(".");

        invTotalLbl.setText(".");

        newInvBtn.setText("Create New Invoice");
        newInvBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newInvBtnActionPerformed(evt);
            }
        });

        deleteInvBtn.setText("Delete Invoice");

        newItemBtn.setText("Add New Item");

        deleteItemBtn.setText("Delete Item");

        invDateLbl.setText(".");

        invCustNameLbl.setText(".");

        file.setText("File");

        loadFile.setText("load file");
        loadFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadFileActionPerformed(evt);
            }
        });
        file.add(loadFile);

        saveChanges.setText("save changes");
        file.add(saveChanges);

        jMenuBar1.add(file);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label3)
                            .addComponent(lable4)
                            .addComponent(label2)
                            .addComponent(label1))
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(invNoLbl)
                            .addComponent(invTotalLbl)
                            .addComponent(invDateLbl)
                            .addComponent(invCustNameLbl))
                        .addGap(296, 296, 296))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))))
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(newInvBtn)
                .addGap(48, 48, 48)
                .addComponent(deleteInvBtn)
                .addGap(153, 153, 153)
                .addComponent(newItemBtn)
                .addGap(66, 66, 66)
                .addComponent(deleteItemBtn)
                .addContainerGap(121, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label1)
                            .addComponent(invNoLbl))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label2)
                            .addComponent(invDateLbl))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label3)
                            .addComponent(invCustNameLbl))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lable4)
                            .addComponent(invTotalLbl))
                        .addGap(44, 44, 44)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newInvBtn)
                    .addComponent(deleteInvBtn)
                    .addComponent(newItemBtn)
                    .addComponent(deleteItemBtn))
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadFileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loadFileActionPerformed

    private void newInvBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newInvBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newInvBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FWD_InvoiceGenerator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FWD_InvoiceGenerator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FWD_InvoiceGenerator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FWD_InvoiceGenerator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new FWD_InvoiceGenerator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteInvBtn;
    private javax.swing.JButton deleteItemBtn;
    private javax.swing.JMenu file;
    private javax.swing.JTable headerTbl;
    private javax.swing.JLabel invCustNameLbl;
    private javax.swing.JLabel invDateLbl;
    private javax.swing.JLabel invNoLbl;
    private javax.swing.JLabel invTotalLbl;
    private javax.swing.JTable itemTbl;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel lable4;
    private javax.swing.JMenuItem loadFile;
    private javax.swing.JButton newInvBtn;
    private javax.swing.JButton newItemBtn;
    private javax.swing.JMenuItem saveChanges;
    // End of variables declaration//GEN-END:variables


    private Controller controller = new Controller(this);
    private ArrayList<InvoiceHeader> invHeaderArray = new ArrayList<>();
    private HeaderTableModel invHeaderTableModel;
    private LineTableModel invLineTableModel;
    private CreateNewInvoiceDialog invoiceDialog;
    private CreateItemDialog lineDialog;


    public Controller getController() {
        return controller;
    }
    public ArrayList<InvoiceHeader> getInvHeaderArray() {
        return invHeaderArray;
    }
    public void setInvHeaderTableModel(HeaderTableModel invHeaderTableModel) {
        this.invHeaderTableModel = invHeaderTableModel;
    }
    public void setInvLineTableModel(LineTableModel invLineTableModel) {
        this.invLineTableModel = invLineTableModel;
    }

    public LineTableModel getInvLineTableModel() {
        return invLineTableModel;
    }
    
    public HeaderTableModel getInvHeaderTableModel(){
       return invHeaderTableModel;
    }
    
    public JTable getHeaderTbl() {
       return headerTbl;
    }
    
    public JTable getItemsTbl() {
        return itemTbl;
    }
    public JLabel getcustLbl() {
        return invCustNameLbl;
    }
    
     public JLabel getNumLbl() {
        return invNoLbl;
    }
    
    public JLabel getInvDateTF() {
        return invDateLbl;
    }
  
    public JLabel getTotalLbl() {
        return invTotalLbl;
    }
    public void setHeaderDialog(CreateNewInvoiceDialog invoiceDialog) {
        this.invoiceDialog = invoiceDialog;
    }

    public CreateNewInvoiceDialog getHeaderDialog() {
        return invoiceDialog;
    }
    public void setLineDialog(CreateItemDialog lineDialog) {
        this.lineDialog = lineDialog;
    }
    public CreateItemDialog getLineDialog() {
        return lineDialog;
    }

}
